---
- name: Install bash_it
  git:
    repo: git@github.com:Bash-it/bash-it.git
    dest: "/home/{{ item.key }}/.bash_it"
    accept_hostkey: yes
    key_file: "/home/{{ item.key }}/.ssh/{{ item.key }}@{{ ansible_facts['hostname'] }}"
  loop: "{{ local_users | dict2items }}"

- name: Bash it theme shim directory
  file:
    path: "/home/{{ item.key }}/.bash_it/themes/do-what-I-say"
    state: directory
  loop: "{{ local_users | dict2items }}"

- name: Bash it theme shim file
  file:
    path: "/home/{{ item.key }}/.bash_it/themes/do-what-I-say/do-what-I-say.theme.bash"
    state: touch
  loop: "{{ local_users | dict2items }}"

- name: Bash it plugins enable
  command: "/bin/bash -i -l -c \"bash-it enable plugin {{ bplugins|join(' ') }}\""
  when: bplugins is defined
  register: plugins_result
  changed_when: "plugins_result.stdout_lines | reject('match', '.* is already enabled.') | list | length > 0"

- name: bash_it aliases enable
  command: "/bin/bash -i -l -c \"bash-it enable alias {{ baliases|join(' ') }}\""
  when: baliases is defined
  register: aliases_result
  changed_when: "aliases_result.stdout_lines | reject('match', '.* is already enabled.') | list | length > 0"

- name: bash_it completions enable
  command: "/bin/bash -i -l -c \"bash-it enable completion {{ bcompletions|join(' ') }}\""
  when: bcompletions is defined
  register: completions_result
  changed_when: "completions_result.stdout_lines | reject('match', '.* is already enabled.') | list | length > 0"
