---
- name: Ensure HOME/dev
  file:
    path: "home/{{ item.key }}/dev"
    state: directory
  loop: "{{ local_users | dict2items }}"
  become_user: tbh

- name: Clone dotfiles
  git:
    repo: git@github.com:t0mmy44-h/stashdot.git
    accept_hostkey: yes
    dest: "/home/{{ item.key }}/dev/stashdot"
    key_file: "/home/{{ item.key }}/.ssh/{{ item.key }}@{{ ansible_facts['hostname'] }}"
  loop: "{{ local_users | dict2items }}"
  become_user: tbh

- name: Install Stow
  community.general.pacman:
    state: present
    name:
      - stow

- name: Dotfiles i3wm
  include_tasks: i3wm.yml

    #- name: Dotfiles alacritty
  # include other yaml

- name: Dotfiles nvim
  include_tasks: nvim.yml
