---
- name: Ensure HOME/dev
  file:
    path: "home/{{ item.key }}/dev"
    state: directory
  loop: "{{ local_users | dict2items }}"

- name: Clone dotfiles
  git:
    repo: git@github.com:t0mmy44-h/stashdot.git
    accept_hostkey: yes
    dest: "/home/{{ item.key }}/dev/stashdot"
    key_file: "/home/{{ item.key }}/.ssh/tbh@{{ ansible_facts['hostname'] }}"
  loop: "{{ local_users | dict2items }}"

- name: Install Stow
  community.general.pacman:
    state: present
    name:
      - stow
