---
- name: Update System
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: Ensure Base
  community.general.pacman:
    name:
      - base
      - base-devel
      - linux
      - linux-firmware
      - sudo
      - netctl
      - lvm2
      - grub
      - reflector
      - man-db
      - man-pages
      - texinfo
      - git
      - docker
      - docker-compose
      - openssh
      - neovim
      - ansible
      - python3
      - python-pip
    state: present

- name: Install Hashicorp Python stuff
  pip:
    name: ansible-modules-hashivault

- name: Install Intel Microcode
  community.general.pacman:
    name: intel-ucode
    state: present
  when: ansible_facts['processor'][1].find("Intel") != -1

- name: Install AMD Microcode
  community.general.pacman:
    name: amd-ucode
    state: present
  when: ansible_facts['processor'][1].find("AMD") != -1

- name: Configure Pacman
  include_tasks: pacman.yml

- name: Add User
  include_tasks: user.yml

# - name: Configure AUR support
#   include_tasks: aur.yml
